### ISSUE TITLE
Annotation's title and subtitle in iOS 13

### ISSUE THREAD

**Issue by PVKonovalov** [thepeaklab/GoogleMapsTileOverlay#6] opened 2019-10-06 15:29 UTC
Title and subtitle for annotations are not present for maps with tiles overlees in iOS 13. For standard Apple map titles and subtitles are shown correctly.

**Comment by sandammeer** [comment] 2019-10-07 07:48
Hello @PVKonovalov, 

I will try to reproduce your problem, can you provide example code on how you added your custom titles and subtitles? 

best regards

**Comment by PVKonovalov** [comment] 2019-10-08 14:34
Hello @sandammeer,
I just compiled with xCode 11.0 and install you project to iPad with iOS 13.1.1. I see that in you code you put the annotation with title and subtitle but I can't see title on the map. I found the same problem in my project too. If I use the standard Apple map I see title. But tittles are vanished if using an overlay map. This problem was founded on iOS 13 but on iOS 12 titles was shown.

**Comment by sandammeer** [comment] 2019-10-09 09:52
Thank you for the informations I will work on a fix for this later today

**Comment by sandammeer** [comment] 2019-10-09 15:03
This actually seems to be a problem with ios 13. 
Before you could add the overlay above roads, so they are below the default labels like so: 
`mapView.add(tileOverlay, level: .aboveRoads)`
Unfortunally this method seems to have no effect anymore on ios 13.

As a quick workaround you can set `canReplaceMapContent` to false on the overlay:
`gmTileOverlay.canReplaceMapContent = false`
This displays the system labels while still showing the custom overlays.

I have also opened a Thread on the Apple Developer Forums regarding this issue, you can follow it here: https://forums.developer.apple.com/message/387246#387246

**Comment by sandammeer** [comment] 2019-10-15 07:27
@PVKonovalov I have now also filed a bug at apple and will inform you about updates

**Comment by PVKonovalov** [comment] 2019-10-15 07:56
Thanks, @sandammeer !

**Comment by PVKonovalov** [comment] 2020-07-30 07:58
Wow! It's fixed at least in version 13.5.1

**Comment by sandammeer** [comment] 2020-07-30 08:00
@PVKonovalov thank you for the update! I reported this bug to apple 10 month ago and i am glad to hear that its finally fixed.

**Closed as completed** 2020-07-30 08:00 UTC
